spring:
  datasource:
    #数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iss_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
